import random

def guess_random_num():
    print('Welcome to Guess the Number game. Try your Luck.')
    print('You have to guess a lucky number between 1 to 100, that has been generated by the system. Good Luck.')

    random_integer = random.randint(1, 100)
    print('Lucky number has been generated for You.')

    i = 0
    no_of_guesses = 1

    while True:
        user_input = int(input('Guess the Number: '))
        if user_input == random_integer:
            print('Congrats! You guessed it.')
            break
        if user_input < random_integer:
            print('Too Low')
        if user_input > random_integer:
            print('Too high')
        else:
            print('Try Again')
        i += 1
        no_of_guesses += 1

    if no_of_guesses < 5:
        print('Good Player')
    elif no_of_guesses < 10:
        print('Average Player')
    else:
        print('Not able to get into grading. ')
    print(f'You guessed it in {no_of_guesses} tries.')
    print('Thanks for playing our Game.')

guess_random_num()